version: '3'

services:
  amazonlinux:
    build:
      context: .
      dockerfile: Dockerfile
    image: packer_test_amazonlinux
    ports:
      - "127.0.0.1:22:22"
    container_name: packer_test_amazonlinux